apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2023-05-03T09:11:07Z'
  generation: 5
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
          'f:volumes': {}
      manager: Mozilla
      operation: Update
      time: '2023-05-05T06:35:16Z'
  name: scan-code
  namespace: cicd
  resourceVersion: '8204659'
  uid: b9a1b509-c81a-4f7e-91f5-7e07be10fada
spec:
  params:
    - default: 'docker.io/sonarsource/sonar-scanner-cli:latest'
      name: sonarqube-cli
      type: string
    - default: >-
        https://sonarqube-sonarqube.apps.cluster-4t99p.4t99p.sandbox2243.opentlc.com/
      name: sonarqubeHostUrl
      type: string
    - name: git-url
      type: string
    - default: master
      name: git-revision
      type: string
    - default: ''
      name: app-name
      type: string
    - default: /source
      name: source-dir
      type: string
  steps:
    - env:
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: git-credentials
              optional: true
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: git-credentials
              optional: true
      image: quay.io/ibmgaragecloud/alpine-git
      name: git-clone
      resources: {}
      script: |
        set +x
        if [[ -n "${GIT_USERNAME}" ]] && [[ -n "${GIT_PASSWORD}" ]]; then
            git clone "$(echo $(params.git-url) | awk -F '://' '{print $1}')://${GIT_USERNAME}:${GIT_PASSWORD}@$(echo $(params.git-url) | awk -F '://' '{print $2}')" $(params.source-dir)
        else
            set -x
            git clone $(params.git-url) $(params.source-dir)
        fi
        set -x
        cd $(params.source-dir)
        git checkout $(params.git-revision)
    - env:
        - name: SONAR_USER_HOME
          value: $(params.source-dir)
        - name: SONARQUBE_URL
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_URL
              name: sonarqube-access
              optional: true
        - name: SONARQUBE_USER
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_USER
              name: sonarqube-access
              optional: true
        - name: SONARQUBE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_PASSWORD
              name: sonarqube-access
              optional: true
      image: $(params.sonarqube-cli)
      name: sonar-scan
      resources: {}
      script: |
        APP_NAME=$(params.app-name)

        if ! command -v sonar-scanner &> /dev/null
        then
            echo "Skipping SonarQube step, no task defined"
            exit 0
        fi

        if [ -n "${SONARQUBE_URL}" ]; then

           sonar-scanner \
            -Dsonar.login=${SONARQUBE_USER} \
            -Dsonar.password=${SONARQUBE_PASSWORD} \
            -Dsonar.host.url=${SONARQUBE_URL} \
            -Dsonar.projectKey=${APP_NAME}

        else
            echo "Skipping Sonar Qube step"
        fi
      workingDir: $(params.source-dir)
  volumes:
    - emptyDir: {}
      name: source
