apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2023-04-27T15:19:35Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-04-27T15:19:35Z'
  name: app-pipeline
  namespace: cicd
spec:
  params:
    #- name: REPO_HOST
    # type: string
    #- name: COMMIT_SHA
     # type: string
    - name: TLSVERIFY
      type: string
    - name: BUILD_EXTRA_ARGS
      type: string
      default: ""
    - name: IMAGE_REPO
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spring-petclinic"
    #- name: MANIFEST_FILE
    # type: string
    #- name: MANIFEST_REPO
    #  type: string
    #- name: MANIFEST_REPO_NAME
     # type: string
    #- name: GIT_REF
     # type: string
    #- name: COMMIT_DATE
    #  type: string
    #- name: COMMIT_AUTHOR
    #  type: string
    #- name: COMMIT_MESSAGE
    #  type: string
    - name: GIT_REPO
      type: string
    - name: SONARQUBE_HOST_URL
      type: string
    - default: ramyarbhat2910@gmail.com
      name: USER_EMAIL
      type: string
    - default: ramragh1
      name: USER_NAME
      type: string
    - default: latest
      name: IMAGE_TAG
      type: string
    - default: mockproject
      name: APP_NAME
      type: string
    - default: 'http://148.64.4.164:8080'
      name: HTTP_PROXY
      type: string
    - default: >-
        10.191.48.101,localhost,bastion.mgmt.infyitapps.local,api.cloud.infyitapps.local,image-registry.openshift-image-registry.svc,.apps.cloud.infyitapps.local
      name: NO_PROXY
      type: string
    - default: 'github.com/RamyaRaghuveera/Ocp-HelmChart.git'
      name: HELM_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: rrbg.jfrog.io/docker-local
      name: JFROG_URL
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/cicd/mockproject
      name: IMAGE_NAME
      type: string
  tasks:
    - name: fetch-source
      params:
        - name: git-url
          value: $(params.GIT_REPO)
        - name: git-revision
          value: $(params.GIT_REVISION)
      taskRef:
        kind: Task
        name: fetch-source
      workspaces:
        - name: output
          workspace: shared-data
    - name: scan-source
      params:
        - name: sonarqubeHostUrl
          value: $(params.SONARQUBE_HOST_URL)
        - name: git-url
          value: $(params.GIT_REPO)
        - name: git-revision
          value: $(params.GIT_REVISION)  
        - name: app-name
          value: $(params.APP_NAME) 
      runAfter:
        - fetch-source
      taskRef:
        kind: Task
        name: scan-code
      workspaces:
       - name: repository
         workspace: shared-data
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: $(params.APP_NAME)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: SKIP_PUSH
          value: 'false'
        - name: httpProxy
          value: $(params.HTTP_PROXY)
        - name: httpsProxy
          value: $(params.HTTP_PROXY)
        - name: JFROG_URL
          value: $(params.JFROG_URL)
        - name: APP_NAME
          value: $(params.APP_NAME)
        - name: noProxy
          value: $(params.NO_PROXY)
        - name: image-namespace
          value: $(context.pipelineRun.namespace) 

      runAfter:
        - scan-source
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data
    - name: skopeo-copy-task
      params:
        - name: destImageURL
          value: $(params.JFROG_URL)
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
        - name: httpProxy
          value: $(params.HTTP_PROXY)
        - name: httpsProxy
          value: $(params.HTTP_PROXY)
        - name: noProxy
          value: $(params.NO_PROXY)
        - name: srcImageURL
          value: $(params.IMAGE_NAME)
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: APP_NAME
          value: $(params.APP_NAME)
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: skopeo-copy-task
      #workspaces:
       # - name: images-url
        #  workspace: shared-data
    - name: acs-image-check
      params:
        - name: rox_central_endpoint
          value: stackrox-endpoint
        - name: rox_api_token
          value: stackrox-secret
        - name: image
          value: '$(params.IMAGE_REPO):$(params.IMAGE_TAG)'
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - skopeo-copy-task
      taskRef:
        kind: Task
        name: acs-image-check
    - name: acs-image-scan
      params:
        - name: rox_central_endpoint
          value: stackrox-endpoint
        - name: rox_api_token
          value: stackrox-secret
        - name: image
          value: '$(params.IMAGE_REPO):$(params.IMAGE_TAG)'
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - skopeo-copy-task
      taskRef:
        kind: Task
        name: acs-image-scan
    - name: acs-deploy-check
      params:
        - name: rox_central_endpoint
          value: stackrox-endpoint
        - name: rox_api_token
          value: stackrox-secret
        - name: gitRepositoryUrl
          value: $(params.HELM_REPO)
          #value: $(params.MANIFEST_REPO)
        - name: gitRepositoryRevision
          value: main
        - name: insecure-skip-tls-verify
          value: 'true'
        - name: app_name
          value: $(params.APP_NAME)
      runAfter:
        - skopeo-copy-task
      taskRef:
        kind: Task
        name: acs-deploy-check
    - name: git-update-deployment
      params:
        - name: url
          value: $(params.HELM_REPO)
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: gitops #temporary value
          #value: $(params.APP_NAME)/helm-chart
        - name: deleteExisting
          value: 'false' #'true'
        - name: httpProxy
          value: $(params.HTTP_PROXY)
        - name: httpsProxy
          value: $(params.HTTP_PROXY)
        - name: KUSTOMIZATION_PATH
          value: application/globex-ui/base #temporary
          #value: app/base
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:cadf614a6044ee37397de3abe7674827ecab225e7fac9fb123eff5473e2c4003
        - name: CURRENT_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/cicd/mockproject
        - name: NEW_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/cicd/mockproject
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: USER_EMAIL
          value: $(params.USER_EMAIL)
        - name: USER_NAME
          value: $(params.USER_NAME)
      runAfter:
        - acs-image-scan
        - acs-deploy-check
        - acs-image-check
      taskRef:
        kind: Task
        name: git-update-deployment
      #workspaces:
        #- name: output
         # workspace: shared-data
  workspaces:
    - name: shared-data
    #- name: maven-settings
    #- name: signature
